### PR TITLE
Geronimp pre merge master

### PR DESCRIPTION
**Pull request by geronimp**
Hopefully all good now.

### CODE REVIEW

**Comment by wwood** [comment]
I don't think we should have usearch as a dependency. Clustering worked before without it, why did you introduce it?

**Comment by geronimp** [comment]
to remove redundant sequences before placement, so that pplacer has to do less work. I can use python instead if you want to remove usearch.


What do you mean clustering did work before without it?


________________________________

**Comment by wwood** [comment]
I already implemented this I thought, that's how I got Fauzi's create to 
work.

**Comment by geronimp** [comment]
Usearch dependency removed, now uses deduplicator

**Comment by wwood** [comment]
```
$ nosetests -x
E
======================================================================
ERROR: Failure: ImportError (No module named cluster)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/sw/nose/1.3.3/lib/python2.7/site-packages/nose-1.3.3-py2.7.egg/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/srv/sw/nose/1.3.3/lib/python2.7/site-packages/nose-1.3.3-py2.7.egg/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/srv/sw/nose/1.3.3/lib/python2.7/site-packages/nose-1.3.3-py2.7.egg/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/srv/home/uqbwoodc/git/graftM/test/test_cluster.py", line 33, in <module>
    from graftm.cluster import readsClusterer
ImportError: No module named cluster

----------------------------------------------------------------------
```

**Comment by wwood** [comment]
actually maybe can just delete that file, hang on

**Comment by wwood** [comment]
but then here's another sorry
```
uqbwoodc@menzies:20150716:~/git/graftM$ nosetests -x
E
======================================================================
ERROR: Failure: ImportError (No module named db_search_results)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/sw/nose/1.3.3/lib/python2.7/site-packages/nose-1.3.3-py2.7.egg/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/srv/sw/nose/1.3.3/lib/python2.7/site-packages/nose-1.3.3-py2.7.egg/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/srv/sw/nose/1.3.3/lib/python2.7/site-packages/nose-1.3.3-py2.7.egg/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/srv/home/uqbwoodc/git/graftM/test/test_create.py", line 31, in <module>
    from graftm.create import Create
  File "/srv/home/uqbwoodc/git/graftM/graftm/create.py", line 13, in <module>
    from graftm.hmmer import Hmmer
  File "/srv/home/uqbwoodc/git/graftM/graftm/hmmer.py", line 22, in <module>
    from graftm.db_search_results import DBSearchResult
ImportError: No module named db_search_results

----------------------------------------------------------------------
```

**Comment by geronimp** [comment]
I just deleted that file and forgot to remove the import. You got this or would you like me to fix?


________________________________

**Comment by wwood** [comment]
I fixed that but then ran into another. Do you mind making sure you have added all the necessary files (ie clean git status) and that nosetests passes please?

**Comment by geronimp** [comment]
try now?

**Comment by wwood** [comment]
Also guessing the GraftM 0.7.0 should not be displayed.
```
      GraftM 0.7.0
Error: function Input_stream::Input_stream(const string&, bool) line 63. 
Error opening file 
/srv/home/uqbwoodc/git/graftM/test/data/create/homologs.trimmed.unaligned.faa
Traceback (most recent call last):
   File "/srv/home/uqbwoodc/git/graftM/test/../bin/graftM", line 224, in 
<module>
     graftm.run.Run(args).main()
   File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/run.py", line 433, 
in main
     taxtastic_seqinfo = self.args.taxtastic_seqinfo
   File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/create.py", line 
424, in main
     subprocess.check_call(cmd, shell=True)
   File "/srv/sw/python/2.7.4/lib/python2.7/subprocess.py", line 542, in 
check_call
     raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'diamond makedb --in 
'/srv/home/uqbwoodc/git/graftM/test/data/create/homologs.trimmed.unaligned.faa' 
-d 'homologs'' returned non-zero exit status 1
E
======================================================================
ERROR: test_hello_world (test_create.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
   File "/srv/home/uqbwoodc/git/graftM/test/test_create.py", line 48, in 
test_hello_world
     subprocess.check_call(cmd1, shell=True)
   File "/srv/sw/python/2.7.4/lib/python2.7/subprocess.py", line 542, in 
check_call
     raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 
'/srv/home/uqbwoodc/git/graftM/test/../bin/graftM create --verbosity 1 
--sequences 
/srv/home/uqbwoodc/git/graftM/test/data/create/homologs.trimmed.unaligned.faa 
--alignment 
/srv/home/uqbwoodc/git/graftM/test/data/create/homologs.trimmed.aligned.faa 
--taxonomy 
/srv/home/uqbwoodc/git/graftM/test/data/create/homologs.tax2tree.rerooted.decorated.tree-consensus-strings 
--rerooted_tree 
/srv/home/uqbwoodc/git/graftM/test/data/create/homologstre.tree --output 
/tmp/tmplaanBo' returned non-zero exit status 1

----------------------------------------------------------------------
```

**Pull request closed without merging**
