### PR TITLE
graftm_package: add is_protein_package method

### PR DESCRIPTION
**Pull request by wwood**
this is useful for singlem..

### CODE REVIEW

**Comment by geronimp** [comment]
Would it not be better just to have this as a field in the CONTENTS.json file?

**Comment by geronimp** [comment]
of the gpkg when its created that is

**Comment by wwood** [comment]
yes, maybe, but I'm just too lazy to update all the gpkgs to another version. Shall we merge this and in v4 implement that as a field?

**Comment by geronimp** [comment]
Sure

Joel

**Pull request merged**
