### PR TITLE
decorate: Add ability to decorate trees with <7 levels of taxonomy.

### PR DESCRIPTION
**Pull request by wwood**
graftm/tree_decorator.py(_transpose_taxonomy): Rename to
_unique_taxonomy. Remove hard-coded expectation of 7 levels.

### CODE REVIEW

**Comment by wwood** [comment]
After applying this, can we delete this part from the __init__  which I guess just pads the taxtastic taxonomy things with empty prefixes? If so we can remove all traces of 7 levels and the prefixes from this class, which I reckon would be a win.
```
            for id, taxonomy_list in self.taxonomy.iteritems():
                if len(taxonomy_list) != MAX_RESOLUTION:
                    self.taxonomy[id] = taxonomy_list + self.gg_prefixes[1:][len(taxonomy_list):]
```

**Comment by geronimp** [comment]
Is this ready to merge?

**Comment by wwood** [comment]
If tests pass then yes. Sorry I got lazy and didn't run them.

**Comment by geronimp** [comment]
It fails on that slash ending test. I'll keep this open till that fix has been merged.

**Comment by wwood** [comment]
If it is OK with you I'd like to merge, since that doesn't really qualify as a test failure.

>After applying this, can we delete this part from the init which I guess just pads the taxtastic taxonomy things with empty prefixes? If so we can remove all traces of 7 levels and the prefixes from this class, which I reckon would be a win.

Agree?

**Comment by geronimp** [comment]
Yep, do you just want to delete that part now as part of this branch?

**Comment by wwood** [comment]
I just did in that commit. However, I am unable to test with much certainty whether it works as there are no unit tests for this class. Do you mind testing this branch out yourself manually, and add some tests in the process please?

**Comment by geronimp** [comment]
Sure

**Comment by wwood** [comment]
Are we happy with this branch?

**Comment by geronimp** [comment]
Yep

**Comment by wwood** [comment]
merged

**Pull request closed without merging**
