### PR TITLE
Geronimp update mode2

### PR DESCRIPTION
**Pull request by geronimp**
Sigh, conflicts.

### CODE REVIEW

**Comment by geronimp** [comment]
Some of these conflicts I'm not sure about because they're in code you were working on. Should we sit down together and do this?

**Comment by wwood** [comment]
sorry I meant merging your code into master, and then update mode, and then dendropy. Is there merge conflicts doing the first step of that?

**Comment by geronimp** [comment]
Hey Ben I think this is good to go btw, I was just waiting on your go ahead

**Comment by wwood** [comment]
Go ahead then, thanks.

**Pull request merged**
