### PR TITLE
Dendropy reannotator

### PR DESCRIPTION
**Pull request by wwood**
Hey,

Now passing all the rerooting tests and all other nosetests too.

This should be backwards-compatible because `Reannotator._reroot_tree_by_old_root` has the same interface.

It actually makes more sense not to do things the 'pull request way' because the two commits do individual things - perhaps makes more sense to go through the commits separately and annotate anything you find in the commits themselves: e.g. write comments on these pages:
https://github.com/geronimp/graftM/commit/23c9afbd9d6348b1e912ce0ed37f1b9366afb7ef
https://github.com/geronimp/graftM/commit/636252d8b81ca41171f3bbc9406b60c703448566

because then you can see exactly what changed in the 2nd commit rather than seeing the move+change at the same time which is what you see if you just look at the '5 changed files'.

thanks for the review.

### CODE REVIEW

**Comment by wwood** [comment]
Hey I fixed that bug I was talking about now, would you mind reviewing please? Thanks.

**Comment by geronimp** [comment]
Hey, did you commit the bugfix?

**Comment by wwood** [comment]
yes, with git commit --amend, git push -f, there's no extra commit

**Comment by geronimp** [comment]
Okay, I see

Joel

**Comment by wwood** [comment]
shall I merge?

**Pull request merged**
