### PR TITLE
Reannotate

### PR DESCRIPTION
**Pull request by wwood**
Some utility methods for "updating" graftm packages in `Create`, but not actually called from the code yet. I'm not quite sure how to integrate this. Some ideas:

* When Create encounters nodes that have not been given taxonomy, reroot the tree by the old tree given in --rerooted-tree or --rerooted-annotated-tree using the code here, then apply your new algorithm, then see if everything is annotated. If so proceed, otherwise ask the user for more info, writing the half annotated tree to a file for the user.

* Might be useful to add an --update option to Create and steal taxonomy, rerooting info etc from there? Should be pretty straightforward I think.

* Add a new "annotate" utility mode (sort of like bootstrap) that takes taxonomy and a rooted tree, or an annotated tree, that reroots and annotates a tree with the code here and your algorithm.

Thoughts?

### CODE REVIEW

**Comment by wwood** [comment]
Maybe not really ready for merge into master, if it doesn't add anything for the user yet. More just trying to draw your attention.

**Comment by geronimp** [comment]
I've branched this branch, and I'm gonna join the code-dots and merge with master afterward. The above ideas are good, but I dont have a hell of a lot of time at the moment, so I'll get as much done as I can.

**Comment by wwood** [comment]
Sure, Np. I can merge, just need your tree annotation code

**Comment by geronimp** [comment]
I've been writing the utility function code, and I'm almost done. Maybe I'll just finish up, and I'll pas it to you?

On that note, I'm running into this error when using the re-rooting script:
                             GraftM 0.7.0
Traceback (most recent call last):
  File "/srv/sw/graftm/0.0.0/bin/graftM", line 262, in <module>
    Run(args).main()
  File "/srv/home/s4293811/04_gits/git_graftM/bin/../graftm/run.py", line 577, in main
    dec.main(self.args.input_taxonomy, self.args.output_tree, self.args.output_taxonomy)
  File "/srv/home/s4293811/04_gits/git_graftM/bin/../graftm/decorator.py", line 72, in main
    self._reroot()
  File "/srv/home/s4293811/04_gits/git_graftM/bin/../graftm/decorator.py", line 52, in _reroot
    self.tree)
  File "/srv/home/s4293811/04_gits/git_graftM/bin/../graftm/reannotator.py", line 54, in _reroot_tree_by_old_root
    new_tree = self._reroot_workaround(new_tree, left_lca)
  File "/srv/home/s4293811/04_gits/git_graftM/bin/../graftm/reannotator.py", line 132, in _reroot_workaround
    if len(nodes_to_remove) != 1: raise Exception("Unexpected number of 1 child nodes")
Exception: Unexpected number of 1 child nodes

What does this mean? I couldn't pick it from the code.

Joel

________________________________

**Comment by wwood** [comment]
On 10 Sep 2015 4:12 pm, "geronimp" <notifications@github.com> wrote:
>
>
> I've been writing the utility function code, and I'm almost done. Maybe
I'll just finish up, and I'll pas it to you?

Sure
>
> On that note, I'm running into this error when using the re-rooting
script:
> GraftM 0.7.0
> Traceback (most recent call last):
> File "/srv/sw/graftm/0.0.0/bin/graftM", line 262, in <module>
> Run(args).main()
> File "/srv/home/s4293811/04_gits/git_graftM/bin/../graftm/run.py", line
577, in main
> dec.main(self.args.input_taxonomy, self.args.output_tree,
self.args.output_taxonomy)
> File "/srv/home/s4293811/04_gits/git_graftM/bin/../graftm/decorator.py",
line 72, in main
> self._reroot()
> File "/srv/home/s4293811/04_gits/git_graftM/bin/../graftm/decorator.py",
line 52, in _reroot
> self.tree)
> File
"/srv/home/s4293811/04_gits/git_graftM/bin/../graftm/reannotator.py", line
54, in _reroot_tree_by_old_root
> new_tree = self._reroot_workaround(new_tree, left_lca)
> File
"/srv/home/s4293811/04_gits/git_graftM/bin/../graftm/reannotator.py", line
132, in _reroot_workaround
> if len(nodes_to_remove) != 1: raise Exception("Unexpected number of 1
child nodes")
> Exception: Unexpected number of 1 child nodes
>
> What does this mean? I couldn't pick it from the code.

Hard to explain, likely a bug in my code. Can you send the tree please?

**Comment by geronimp** [comment]
I've pushed my latest version just now

________________________________

**Pull request merged**
